package source

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/XSAM/otelsql"
	"go.opentelemetry.io/otel/attribute"

	_ "github.com/jackc/pgx/v5/stdlib" // PostgreSQL, for the deployed instance
	_ "modernc.org/sqlite"             // SQLite, pure Go: no cgo, so the image stays small

	"github.com/wncservices/domestique/apps/api/internal/dbx"
	"github.com/wncservices/domestique/apps/api/internal/elevation"
	"github.com/wncservices/domestique/apps/api/internal/gpx"
	"github.com/wncservices/domestique/apps/api/internal/model"
)

// maxGPXBytes caps an upload. Real routes are a few hundred kB; anything past
// this is a mistake or an attack, and we would rather say so than buffer it.
const maxGPXBytes = 20 << 20 // 20 MiB

// routesSchema is the route table, in whichever types the engine uses.
func routesSchema(d dbx.Dialect) string {
	return fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS routes (
    slug         TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    description  TEXT NOT NULL DEFAULT '',
    tags         TEXT NOT NULL DEFAULT '',
    targets      TEXT,
    enabled      %s NOT NULL DEFAULT TRUE,
    sport        TEXT NOT NULL DEFAULT 'cycling',
    gpx          %s NOT NULL,
    distance_m   DOUBLE PRECISION NOT NULL,
    ascent_m     DOUBLE PRECISION NOT NULL,
    start_lat    DOUBLE PRECISION NOT NULL,
    start_lng    DOUBLE PRECISION NOT NULL,
    point_count  INTEGER NOT NULL,
    content_hash TEXT NOT NULL,
    uploaded_by  TEXT NOT NULL DEFAULT '',
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL
);`, d.Boolean, d.Blob)
}

// DB stores routes as rows, with the GPX itself as a blob. This is the mode
// where riders upload through the web UI instead of committing files.
type DB struct {
	db      *sql.DB
	dsn     string
	dialect dbx.Dialect
	// elevation backfills a route's elevation at create/update time when it
	// has none of its own worth trusting (gpx.NeedsElevation) — nil unless
	// SetElevationClient is called, which main.go only does when an
	// operator opts into config.ElevationConfig.Enabled. A directory-backed
	// source never gets one: it has no Create/Update to backfill during.
	elevation *elevation.Client
}

// SetElevationClient wires up elevation backfilling for every future
// Create/Update — a setter rather than a constructor parameter, since it is
// optional and OpenDB's signature is already relied on with a fixed shape
// throughout this codebase and its tests.
func (d *DB) SetElevationClient(c *elevation.Client) {
	d.elevation = c
}

// OpenDB opens (and migrates) a route database.
//
// The DSN decides the engine: a postgres:// URL (or a key=value connection
// string) means PostgreSQL, anything else is a SQLite file path. ":memory:"
// works for tests.
func OpenDB(dsn string) (*DB, error) {
	d, err := dbx.For(dsn)
	if err != nil {
		return nil, err
	}

	connString := dsn
	if d.Name == dbx.SQLite.Name {
		// Create the parent directory: the obvious DSN is ./data/domestique.db,
		// and SQLite will not make the directory itself.
		// #nosec G703 -- the DSN is operator configuration (a flag, the config
		// file, or DOMESTIQUE_SOURCE_DSN), never user input.
		if dir := filepath.Dir(dsn); dir != "" && dir != "." && !strings.Contains(dsn, ":memory:") {
			if mkErr := os.MkdirAll(dir, 0o750); mkErr != nil {
				return nil, fmt.Errorf("create %s: %w", dir, mkErr)
			}
		}
		// WAL keeps a reader (the UI) from blocking a writer (an upload).
		connString = dsn + "?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)"
	}

	db, err := otelsql.Open(d.Driver, connString, otelsql.WithAttributes(attribute.String("db.system", d.Name)))
	if err != nil {
		return nil, err
	}
	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("open %s: %w", dbx.Redact(dsn), err)
	}
	if _, err := db.Exec(routesSchema(d)); err != nil {
		return nil, fmt.Errorf("migrate %s: %w", dbx.Redact(dsn), err)
	}

	store := &DB{db: db, dsn: dsn, dialect: d}
	if err := store.addSportColumn(); err != nil {
		return nil, fmt.Errorf("migrate %s: %w", dbx.Redact(dsn), err)
	}
	if err := store.clearAutoGeneratedDescriptions(context.Background()); err != nil {
		return nil, fmt.Errorf("clean up auto-generated descriptions in %s: %w", dbx.Redact(dsn), err)
	}
	if err := store.normalizeExistingOwners(context.Background()); err != nil {
		return nil, fmt.Errorf("normalize route owners in %s: %w", dbx.Redact(dsn), err)
	}
	return store, nil
}

// normalizeExistingOwners lowercases and trims uploaded_by on every row that
// is not already in that form — Create/Update do this for anything written
// from here on, but a route stored before that (an early --owner CLI
// import, most concretely) keeps whatever casing it was given until this
// runs. Safe to run unconditionally on every startup: uploaded_by carries no
// uniqueness constraint (slug is the table's only key), so two rows for the
// same rider under different casing just both end up correct, never a
// conflict — unlike crew_members.rider, which is part of a composite
// primary key and is deliberately left alone here; MemberSet.Has being
// case-insensitive is what covers that table instead.
func (d *DB) normalizeExistingOwners(ctx context.Context) error {
	_, err := d.db.ExecContext(ctx, d.query(`
        UPDATE routes SET uploaded_by = LOWER(TRIM(uploaded_by))
        WHERE uploaded_by <> LOWER(TRIM(uploaded_by))`))
	return err
}

// addSportColumn adds sport to a routes table that predates the column —
// CREATE TABLE IF NOT EXISTS above is a no-op against a table that already
// exists, so a genuinely new column needs its own step, the same pattern
// internal/crew's addAutoShareColumn and addOriginColumn already use for
// exactly this. Defaulting to 'cycling' is correct for every pre-existing
// row: this library was cycling-only before this column existed, so there
// is nothing to infer, only a default to state (model.SportCycling's own
// zero-value fallback says the same thing at the Go level).
func (d *DB) addSportColumn() error {
	_, err := d.db.Exec(`ALTER TABLE routes ADD COLUMN sport TEXT NOT NULL DEFAULT 'cycling'`)
	if err == nil {
		return nil
	}
	msg := strings.ToLower(err.Error())
	if strings.Contains(msg, "duplicate column") || strings.Contains(msg, "already exists") {
		return nil
	}
	return err
}

// clearAutoGeneratedDescriptions blanks out the description this app itself
// used to stamp on every Komoot import and Garmin sync-back — "Imported
// from Komoot (tour 2030514247)", "Synced back from Garmin (course
// 454821206)" — never useful to a rider, and redundant with the
// "komoot"/"garmin" tag already sitting right below it on the card. Runs on
// every startup, the same idempotent-migration shape as the schema DDL
// above: a no-op once the affected rows are gone, since new imports (see
// internal/api/komoot.go and garmincourses.go) no longer set this text in
// the first place.
func (d *DB) clearAutoGeneratedDescriptions(ctx context.Context) error {
	_, err := d.db.ExecContext(ctx, d.query(`
        UPDATE routes SET description = ''
        WHERE description LIKE 'Imported from Komoot (tour %'
           OR description LIKE 'Synced back from Garmin (course %'`))
	return err
}

// Conn exposes the underlying connection so the sync state can share it
// rather than opening a second one to the same database.
func (d *DB) Conn() *sql.DB { return d.db }

// DSN is the connection string this was opened with. It carries a password;
// use dbx.Redact before showing it to anyone.
func (d *DB) DSN() string { return d.dsn }

// query rewrites the `?` placeholders for the engine in use.
func (d *DB) query(q string) string { return d.dialect.Rebind(q) }

func (d *DB) Close() error { return d.db.Close() }

// Describe names the source for humans. The DSN can carry a password, so it is
// redacted — this string reaches the log and the web UI.
func (d *DB) Describe() string {
	return fmt.Sprintf("%s database %s", d.dialect.Name, dbx.Redact(d.dsn))
}

func (d *DB) List(ctx context.Context) ([]model.Route, []string, error) {
	rows, err := d.db.QueryContext(ctx, d.query(`
        SELECT slug, name, description, tags, targets, enabled, sport,
               distance_m, ascent_m, start_lat, start_lng, point_count,
               content_hash, updated_at, uploaded_by
        FROM routes WHERE enabled = TRUE ORDER BY slug`))
	if err != nil {
		return nil, nil, err
	}
	defer func() { _ = rows.Close() }()

	var routes []model.Route
	for rows.Next() {
		var (
			route   model.Route
			tags    string
			targets sql.NullString
			enabled bool
			sport   string
		)
		if err := rows.Scan(
			&route.Slug, &route.Name, &route.Description, &tags, &targets, &enabled, &sport,
			&route.Stats.DistanceM, &route.Stats.AscentM,
			&route.Stats.StartLat, &route.Stats.StartLng, &route.Stats.PointCount,
			&route.ContentHash, &route.UpdatedAt, &route.Owner,
		); err != nil {
			return nil, nil, err
		}
		route.Tags = splitList(tags)
		route.Enabled = &enabled
		route.Sport = model.Sport(sport)
		if targets.Valid {
			list := splitList(targets.String)
			route.Targets = &list
		}
		route.Origin = "database"
		routes = append(routes, route)
	}
	return routes, nil, rows.Err()
}

func (d *DB) Track(ctx context.Context, slug string) ([]gpx.Point, error) {
	raw, err := d.GPX(ctx, slug)
	if err != nil {
		return nil, err
	}
	return gpx.ParsePoints(raw)
}

func (d *DB) GPX(ctx context.Context, slug string) ([]byte, error) {
	var raw []byte
	err := d.db.QueryRowContext(ctx, d.query(`SELECT gpx FROM routes WHERE slug = ?`), slug).Scan(&raw)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	return raw, err
}

// ElevationConfigured reports whether SetElevationClient has ever been
// called — see this type's own elevation field doc comment for why that is
// optional.
func (d *DB) ElevationConfigured() bool {
	return d.elevation != nil
}

// RecalculateElevation re-runs elevation backfill against a route's own
// currently stored GPX — the only way to fix a route uploaded before this
// feature existed, or one uploaded while the configured terrain service
// happened to be briefly down (backfillElevation swallows that failure by
// design; see its own doc comment). It needs no elevation-specific logic
// of its own: analyse (called from Update below, since GPX is non-nil)
// already re-parses points and re-runs backfillElevation whenever
// gpx.NeedsElevation says the file still has none of its own worth
// trusting, so handing the route's own GPX back to Update is the entire
// implementation. Safe to call on a route that already has real
// elevation — NeedsElevation says no, backfillElevation is skipped, and
// the route comes back with the exact same stats it had before.
func (d *DB) RecalculateElevation(ctx context.Context, slug string) (model.Route, error) {
	raw, err := d.GPX(ctx, slug)
	if err != nil {
		return model.Route{}, err
	}
	return d.Update(ctx, slug, UpdateRequest{GPX: raw})
}

func (d *DB) Create(ctx context.Context, req CreateRequest) (model.Route, error) {
	points, stats, err := d.analyse(ctx, req.GPX)
	if err != nil {
		return model.Route{}, err
	}

	name := strings.TrimSpace(req.Name)
	if name == "" {
		name = Titleize(strings.TrimSuffix(filepath.Base(req.Filename), filepath.Ext(req.Filename)))
	}
	if name == "" {
		name = "Untitled route"
	}

	slug, err := d.uniqueSlug(ctx, Slugify(name))
	if err != nil {
		return model.Route{}, err
	}

	sport := req.Sport
	if sport == "" {
		sport = model.SportCycling
	}

	now := time.Now().UTC().Format(time.RFC3339)
	_, err = d.db.ExecContext(ctx, d.query(`
        INSERT INTO routes (slug, name, description, tags, targets, enabled, sport, gpx,
                            distance_m, ascent_m, start_lat, start_lng, point_count,
                            content_hash, uploaded_by, created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, TRUE, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`),
		slug, name, req.Descript, joinList(req.Tags), nullableList(req.Targets), string(sport), req.GPX,
		stats.DistanceM, stats.AscentM, stats.StartLat, stats.StartLng, stats.PointCount,
		gpx.ContentHash(points, name, req.Descript), normalizeRider(req.UploadedBy), now, now)
	if err != nil {
		return model.Route{}, err
	}

	return d.get(ctx, slug)
}

func (d *DB) Update(ctx context.Context, slug string, req UpdateRequest) (model.Route, error) {
	current, err := d.get(ctx, slug)
	if err != nil {
		return model.Route{}, err
	}

	if req.Name != nil {
		current.Name = strings.TrimSpace(*req.Name)
	}
	if req.Descript != nil {
		current.Description = *req.Descript
	}
	if req.Tags != nil {
		current.Tags = *req.Tags
	}
	if req.Targets != nil {
		current.Targets = req.Targets
	}
	if req.Enabled != nil {
		current.Enabled = req.Enabled
	}
	if req.Owner != nil {
		current.Owner = normalizeRider(*req.Owner)
	}
	if req.Sport != nil {
		current.Sport = *req.Sport
	}

	now := time.Now().UTC().Format(time.RFC3339)

	// claimGuard is appended to the WHERE clause of whichever UPDATE below
	// actually runs, and checked against RowsAffected afterward — see
	// UpdateRequest.ClaimOwner's own doc comment for why a plain
	// read-then-write is not enough here.
	claimGuard := ""
	if req.ClaimOwner {
		claimGuard = " AND uploaded_by = ''"
	}

	if req.GPX != nil {
		points, stats, err := d.analyse(ctx, req.GPX)
		if err != nil {
			return model.Route{}, err
		}
		current.Stats = stats
		current.ContentHash = gpx.ContentHash(points, current.Name, current.Description)
		result, err := d.db.ExecContext(ctx, d.query(`
            UPDATE routes SET name=?, description=?, tags=?, targets=?, enabled=?, sport=?, gpx=?,
                   distance_m=?, ascent_m=?, start_lat=?, start_lng=?, point_count=?,
                   content_hash=?, uploaded_by=?, updated_at=?
            WHERE slug=?`+claimGuard),
			current.Name, current.Description, joinList(current.Tags),
			nullableList(current.Targets), current.IsEnabled(), string(current.EffectiveSport()), req.GPX,
			stats.DistanceM, stats.AscentM, stats.StartLat, stats.StartLng, stats.PointCount,
			current.ContentHash, current.Owner, now, slug)
		if err != nil {
			return model.Route{}, err
		}
		if req.ClaimOwner {
			if affected, _ := result.RowsAffected(); affected == 0 {
				return model.Route{}, ErrAlreadyOwned
			}
		}
		return d.get(ctx, slug)
	}

	// Metadata-only edit. The name feeds the content hash — a rename is a real
	// change as far as the providers are concerned — so recompute it.
	points, err := d.Track(ctx, slug)
	if err != nil {
		return model.Route{}, err
	}
	current.ContentHash = gpx.ContentHash(points, current.Name, current.Description)

	result, err := d.db.ExecContext(ctx, d.query(`
        UPDATE routes SET name=?, description=?, tags=?, targets=?, enabled=?, sport=?,
               content_hash=?, uploaded_by=?, updated_at=?
        WHERE slug=?`+claimGuard),
		current.Name, current.Description, joinList(current.Tags),
		nullableList(current.Targets), current.IsEnabled(), string(current.EffectiveSport()),
		current.ContentHash, current.Owner, now, slug)
	if err != nil {
		return model.Route{}, err
	}
	if req.ClaimOwner {
		if affected, _ := result.RowsAffected(); affected == 0 {
			return model.Route{}, ErrAlreadyOwned
		}
	}
	return d.get(ctx, slug)
}

func (d *DB) Delete(ctx context.Context, slug string) error {
	result, err := d.db.ExecContext(ctx, d.query(`DELETE FROM routes WHERE slug = ?`), slug)
	if err != nil {
		return err
	}
	if affected, _ := result.RowsAffected(); affected == 0 {
		return ErrNotFound
	}
	return nil
}

func (d *DB) get(ctx context.Context, slug string) (model.Route, error) {
	var (
		route   model.Route
		tags    string
		targets sql.NullString
		enabled bool
		sport   string
	)
	err := d.db.QueryRowContext(ctx, d.query(`
        SELECT slug, name, description, tags, targets, enabled, sport,
               distance_m, ascent_m, start_lat, start_lng, point_count,
               content_hash, updated_at, uploaded_by
        FROM routes WHERE slug = ?`), slug).Scan(
		&route.Slug, &route.Name, &route.Description, &tags, &targets, &enabled, &sport,
		&route.Stats.DistanceM, &route.Stats.AscentM,
		&route.Stats.StartLat, &route.Stats.StartLng, &route.Stats.PointCount,
		&route.ContentHash, &route.UpdatedAt, &route.Owner)
	if errors.Is(err, sql.ErrNoRows) {
		return model.Route{}, ErrNotFound
	}
	if err != nil {
		return model.Route{}, err
	}

	route.Tags = splitList(tags)
	route.Enabled = &enabled
	route.Sport = model.Sport(sport)
	if targets.Valid {
		list := splitList(targets.String)
		route.Targets = &list
	}
	route.Origin = "database"
	return route, nil
}

// uniqueSlug appends -2, -3, … so two rides up the same hill can share a name.
func (d *DB) uniqueSlug(ctx context.Context, base string) (string, error) {
	if base == "" {
		base = "route"
	}
	candidate := base
	for attempt := 2; attempt < 1000; attempt++ {
		var exists int
		err := d.db.QueryRowContext(ctx,
			d.query(`SELECT COUNT(1) FROM routes WHERE slug = ?`), candidate).Scan(&exists)
		if err != nil {
			return "", err
		}
		if exists == 0 {
			return candidate, nil
		}
		candidate = fmt.Sprintf("%s-%d", base, attempt)
	}
	return "", fmt.Errorf("could not find a free slug for %q", base)
}

func (d *DB) analyse(ctx context.Context, raw []byte) ([]gpx.Point, model.RouteStats, error) {
	if len(raw) == 0 {
		return nil, model.RouteStats{}, errors.New("empty GPX upload")
	}
	if len(raw) > maxGPXBytes {
		return nil, model.RouteStats{}, fmt.Errorf("GPX is %d bytes, over the %d byte limit",
			len(raw), maxGPXBytes)
	}
	points, err := gpx.ParsePoints(raw)
	if err != nil {
		return nil, model.RouteStats{}, err
	}
	if gpx.NeedsElevation(points) {
		d.backfillElevation(ctx, points)
	}
	return points, gpx.ComputeStats(points), nil
}

// maxElevationLookups caps how many of a route's points ever get a real
// terrain lookup — a recorded track can hold thousands, and an elevation
// profile does not need one sample per GPS fix to sum a climb correctly.
// Sampled evenly across the route; see backfillElevation for why every
// point NOT selected has its own elevation explicitly cleared rather than
// left however gpx.ParsePoints found it.
const maxElevationLookups = 300

// backfillElevation looks up real terrain for an evenly-sampled subset of
// points and applies it to points in place.
//
// Downsampled rather than looking up every point, both for speed (an
// upload is a synchronous HTTP request; thousands of points would mean
// dozens of round trips to a third party before it could ever return) and
// because gpx.ComputeStats does not need one sample per GPS fix to sum a
// climb correctly. Every point *not* selected has HasEle explicitly
// cleared — even though gpx.NeedsElevation already established every
// point in this particular call either had none or the same 0.00000
// placeholder, leaving that placeholder in place on the unsampled points
// would have gpx.ComputeStats read the gap between a real, looked-up
// sample and its untouched 0-elevation neighbour as a climb or a drop
// that was never really there.
//
// Best-effort: any failure (the service unreachable, slow, a bad
// response) is swallowed and points is left exactly as gpx.ParsePoints
// produced it. This must never turn a third party being briefly down
// into a failed upload — the caller already treats "no usable elevation"
// as a legitimate, expected outcome (it is what routing here at all
// means), so there is nothing worse about leaving it that way than there
// was before this feature existed.
//
// backfillTimeout bounds the whole attempt, not just elevation.Client's
// own per-request timeout — up to three sequential batched requests
// (maxElevationLookups points at 100 per request) could otherwise each
// take the client's own full 20s before failing, adding up to a full
// minute to a single, synchronous upload if the configured service is
// merely slow rather than cleanly down. This must finish well inside
// that, or fail, so a degraded elevation service degrades this feature
// quickly instead of making every upload feel hung.
// A var, not a const: elevation_backfill_test.go shrinks it to keep its own
// timeout test fast rather than actually waiting 15 real seconds.
var backfillTimeout = 15 * time.Second

func (d *DB) backfillElevation(ctx context.Context, points []gpx.Point) {
	if d.elevation == nil || len(points) == 0 {
		return
	}
	ctx, cancel := context.WithTimeout(ctx, backfillTimeout)
	defer cancel()

	step := 1
	if len(points) > maxElevationLookups {
		step = (len(points) + maxElevationLookups - 1) / maxElevationLookups
	}

	indices := make([]int, 0, maxElevationLookups+1)
	lookup := make([]elevation.Point, 0, maxElevationLookups+1)
	for i := 0; i < len(points); i += step {
		indices = append(indices, i)
		lookup = append(lookup, elevation.Point{Lat: points[i].Lat, Lon: points[i].Lon})
	}

	elevations, err := d.elevation.Lookup(ctx, lookup)
	if err != nil {
		return
	}

	sampled := make(map[int]bool, len(indices))
	for j, i := range indices {
		points[i].Ele, points[i].HasEle = elevations[j], true
		sampled[i] = true
	}
	for i := range points {
		if !sampled[i] {
			points[i].HasEle = false
		}
	}
}

// Titleize turns a filename stem into a display name:
// "kemmelberg-loop" -> "Kemmelberg Loop".
func Titleize(slug string) string {
	words := strings.Split(strings.ReplaceAll(slug, "_", "-"), "-")
	for i, w := range words {
		if w == "" {
			continue
		}
		words[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(words, " ")
}

var nonSlug = regexp.MustCompile(`[^a-z0-9]+`)

// Slugify turns a display name into a URL-safe slug.
func Slugify(name string) string {
	return strings.Trim(nonSlug.ReplaceAllString(strings.ToLower(name), "-"), "-")
}

func splitList(raw string) []string {
	if strings.TrimSpace(raw) == "" {
		return nil
	}
	parts := strings.Split(raw, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if trimmed := strings.TrimSpace(p); trimmed != "" {
			out = append(out, trimmed)
		}
	}
	return out
}

func joinList(items []string) string { return strings.Join(items, ",") }

// normalizeRider is the canonical form a rider identifier gets before it is
// ever stored as a route's owner — lowercased and trimmed, the same
// transformation identityFromToken already applies to every OIDC claim
// before it becomes an Identity.User, and internal/crew's own copy applies
// to crew membership for the identical reason: two paths writing the same
// real rider with different casing (a typed CLI --owner flag vs. a signed-in
// session) must resolve to the same value, or crew-membership and route-edit
// checks — one case-insensitive (auth.Identity.CanEditRoute), one exact
// (crew.MemberSet.Has, before it also became case-insensitive) — silently
// disagree about who a route belongs to.
func normalizeRider(s string) string { return strings.ToLower(strings.TrimSpace(s)) }

func nullableList(items *[]string) any {
	if items == nil {
		return nil
	}
	return joinList(*items)
}
