package source

import (
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// openTestDB opens a SQLite database. Most tests use this; TestEachEngine runs
// the behavioural suite against PostgreSQL as well.
func openTestDB(t *testing.T) *DB {
	t.Helper()
	db, err := OpenDB(filepath.Join(t.TempDir(), "test.db"))
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	t.Cleanup(func() { db.Close() })
	return db
}

// postgresDSN is where the tests find a PostgreSQL to exercise.
//
// PostgreSQL is what this runs against in the cluster, so "it works on SQLite"
// is not enough: placeholders, the boolean column and the blob type all differ.
// Set DOMESTIQUE_TEST_POSTGRES to a DSN to include it; CI does.
const postgresEnv = "DOMESTIQUE_TEST_POSTGRES"

func openTestPostgres(t *testing.T) *DB {
	t.Helper()

	dsn := os.Getenv(postgresEnv)
	if dsn == "" {
		t.Skipf("set %s to a PostgreSQL DSN to run this", postgresEnv)
	}

	db, err := OpenDB(dsn)
	if err != nil {
		t.Fatalf("open postgres: %v", err)
	}
	// Each test gets a clean table; they share one database.
	if _, err := db.db.Exec(`DROP TABLE IF EXISTS routes`); err != nil {
		t.Fatalf("reset schema: %v", err)
	}
	if _, err := db.db.Exec(routesSchema(db.dialect)); err != nil {
		t.Fatalf("recreate schema: %v", err)
	}

	t.Cleanup(func() { db.Close() })
	return db
}

func exampleGPX(t *testing.T) []byte {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "kemmelberg-loop.gpx"))
	if err != nil {
		t.Fatal(err)
	}
	return raw
}

func TestDBCreateDerivesStatsAndSlug(t *testing.T) {
	db := openTestDB(t)

	route, err := db.Create(t.Context(), CreateRequest{
		Filename: "kemmelberg-loop.gpx",
		GPX:      exampleGPX(t),
	})
	if err != nil {
		t.Fatalf("create: %v", err)
	}

	if route.Slug != "kemmelberg-loop" {
		t.Errorf("slug = %q, want kemmelberg-loop derived from the filename", route.Slug)
	}
	if route.Name != "Kemmelberg Loop" {
		t.Errorf("name = %q, want a titleized filename", route.Name)
	}
	if route.Stats.PointCount == 0 || route.Stats.DistanceM == 0 {
		t.Errorf("stats not derived on upload: %+v", route.Stats)
	}
	if route.ContentHash == "" {
		t.Error("content hash not computed; the diff engine would never see a change")
	}
}

// A rider's real description must survive the cleanup; only the app's own
// auto-generated sentence gets blanked, and only on a genuine reopen (a
// second process startup against the same file) — not retroactively wiped
// out from under an already-running one.
func TestOpenDBClearsOnlyAutoGeneratedDescriptions(t *testing.T) {
	path := filepath.Join(t.TempDir(), "test.db")
	db, err := OpenDB(path)
	if err != nil {
		t.Fatalf("open db: %v", err)
	}

	imported, err := db.Create(t.Context(), CreateRequest{
		Name: "Old Komoot Import", Descript: "Imported from Komoot (tour 2030514247)", GPX: exampleGPX(t),
	})
	if err != nil {
		t.Fatalf("create: %v", err)
	}
	synced, err := db.Create(t.Context(), CreateRequest{
		Name: "Old Garmin Sync", Descript: "Synced back from Garmin (course 454821206)", GPX: exampleGPX(t),
	})
	if err != nil {
		t.Fatalf("create: %v", err)
	}
	real, err := db.Create(t.Context(), CreateRequest{
		Name: "Hand-Written", Descript: "My favourite loop through the Ardennes", GPX: exampleGPX(t),
	})
	if err != nil {
		t.Fatalf("create: %v", err)
	}
	db.Close()

	reopened, err := OpenDB(path)
	if err != nil {
		t.Fatalf("reopen db: %v", err)
	}
	defer reopened.Close()

	routes, _, err := reopened.List(t.Context())
	if err != nil {
		t.Fatalf("list: %v", err)
	}
	byName := map[string]string{}
	for _, r := range routes {
		byName[r.Name] = r.Description
	}
	if byName[imported.Name] != "" {
		t.Errorf("Komoot description = %q, want cleared", byName[imported.Name])
	}
	if byName[synced.Name] != "" {
		t.Errorf("Garmin description = %q, want cleared", byName[synced.Name])
	}
	if byName[real.Name] != "My favourite loop through the Ardennes" {
		t.Errorf("hand-written description = %q, want it untouched", byName[real.Name])
	}
}

func TestDBCreateRejectsBadGPX(t *testing.T) {
	db := openTestDB(t)

	for name, body := range map[string][]byte{
		"empty":     {},
		"not xml":   []byte("this is not a GPX file"),
		"one point": []byte(`<gpx version="1.1"><trk><trkseg><trkpt lat="50" lon="3"/></trkseg></trk></gpx>`),
	} {
		if _, err := db.Create(t.Context(), CreateRequest{Filename: name + ".gpx", GPX: body}); err == nil {
			t.Errorf("%s: expected an error, got none", name)
		}
	}
}

// Two rides up the same hill should both be storable.
func TestDBCreateDisambiguatesSlugs(t *testing.T) {
	db := openTestDB(t)
	raw := exampleGPX(t)

	first, err := db.Create(t.Context(), CreateRequest{Name: "Kemmelberg Loop", GPX: raw})
	if err != nil {
		t.Fatal(err)
	}
	second, err := db.Create(t.Context(), CreateRequest{Name: "Kemmelberg Loop", GPX: raw})
	if err != nil {
		t.Fatal(err)
	}

	if first.Slug == second.Slug {
		t.Fatalf("both routes got slug %q", first.Slug)
	}
	if second.Slug != "kemmelberg-loop-2" {
		t.Errorf("second slug = %q, want kemmelberg-loop-2", second.Slug)
	}
}

func TestDBRenameChangesContentHash(t *testing.T) {
	db := openTestDB(t)

	route, err := db.Create(t.Context(), CreateRequest{Name: "Before", GPX: exampleGPX(t)})
	if err != nil {
		t.Fatal(err)
	}

	renamed := "After"
	updated, err := db.Update(t.Context(), route.Slug, UpdateRequest{Name: &renamed})
	if err != nil {
		t.Fatalf("update: %v", err)
	}

	// The providers show the name, so a rename has to reach them.
	if updated.ContentHash == route.ContentHash {
		t.Error("content hash unchanged after a rename; the rename would never sync")
	}
}

func TestDBListSkipsDisabledRoutes(t *testing.T) {
	db := openTestDB(t)

	route, err := db.Create(t.Context(), CreateRequest{Name: "Hidden", GPX: exampleGPX(t)})
	if err != nil {
		t.Fatal(err)
	}

	disabled := false
	if _, err := db.Update(t.Context(), route.Slug, UpdateRequest{Enabled: &disabled}); err != nil {
		t.Fatal(err)
	}

	routes, _, err := db.List(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if len(routes) != 0 {
		t.Fatalf("got %d routes, want 0 — disabled routes must not sync", len(routes))
	}
}

func TestDBDeleteAndMissingLookups(t *testing.T) {
	db := openTestDB(t)

	route, err := db.Create(t.Context(), CreateRequest{Name: "Doomed", GPX: exampleGPX(t)})
	if err != nil {
		t.Fatal(err)
	}
	if err := db.Delete(t.Context(), route.Slug); err != nil {
		t.Fatalf("delete: %v", err)
	}

	if err := db.Delete(t.Context(), route.Slug); !errors.Is(err, ErrNotFound) {
		t.Errorf("second delete: err = %v, want ErrNotFound", err)
	}
	if _, err := db.GPX(t.Context(), route.Slug); !errors.Is(err, ErrNotFound) {
		t.Errorf("GPX after delete: err = %v, want ErrNotFound", err)
	}
}

func TestDBRoundTripsTargets(t *testing.T) {
	db := openTestDB(t)

	only := []string{"garmin:wilant"}
	route, err := db.Create(t.Context(), CreateRequest{Name: "Private", GPX: exampleGPX(t), Targets: &only})
	if err != nil {
		t.Fatal(err)
	}

	routes, _, err := db.List(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if len(routes) != 1 || routes[0].Targets == nil {
		t.Fatalf("targets lost on the way to the database: %+v", routes)
	}
	if got := *routes[0].Targets; len(got) != 1 || got[0] != "garmin:wilant" {
		t.Errorf("targets = %v, want [garmin:wilant]", got)
	}
	_ = route
}

// ---------- both engines ----------

// The behavioural suite, run against every engine we support. SQLite and
// PostgreSQL disagree on placeholders, booleans and blob types, so passing on
// one says nothing about the other — and PostgreSQL is the one this runs
// against in the cluster.
func TestEachEngine(t *testing.T) {
	engines := map[string]func(*testing.T) *DB{
		"sqlite":   openTestDB,
		"postgres": openTestPostgres,
	}

	for engine, open := range engines {
		t.Run(engine, func(t *testing.T) {
			t.Run("create and read back", func(t *testing.T) {
				db := open(t)

				route, err := db.Create(t.Context(), CreateRequest{
					Filename:   "kemmelberg-loop.gpx",
					Descript:   "Cobbles",
					Tags:       []string{"gravel", "hills"},
					UploadedBy: "wilant",
					GPX:        exampleGPX(t),
				})
				if err != nil {
					t.Fatalf("create: %v", err)
				}
				if route.Slug != "kemmelberg-loop" {
					t.Errorf("slug = %q", route.Slug)
				}
				if route.Stats.DistanceM == 0 || route.ContentHash == "" {
					t.Errorf("stats not derived: %+v", route.Stats)
				}
				if route.Owner != "wilant" {
					t.Errorf("owner = %q, want wilant", route.Owner)
				}
				if len(route.Tags) != 2 {
					t.Errorf("tags = %v", route.Tags)
				}

				// The GPX blob has to survive the round trip byte for byte, or
				// the file that reaches the device is not the one uploaded.
				raw, err := db.GPX(t.Context(), route.Slug)
				if err != nil {
					t.Fatalf("GPX: %v", err)
				}
				if string(raw) != string(exampleGPX(t)) {
					t.Error("the stored GPX differs from what was uploaded")
				}
			})

			t.Run("list skips disabled", func(t *testing.T) {
				db := open(t)

				visible, err := db.Create(t.Context(), CreateRequest{Name: "Visible", GPX: exampleGPX(t)})
				if err != nil {
					t.Fatal(err)
				}
				hidden, err := db.Create(t.Context(), CreateRequest{Name: "Hidden", GPX: exampleGPX(t)})
				if err != nil {
					t.Fatal(err)
				}

				off := false
				if _, err := db.Update(t.Context(), hidden.Slug, UpdateRequest{Enabled: &off}); err != nil {
					t.Fatal(err)
				}

				routes, _, err := db.List(t.Context())
				if err != nil {
					t.Fatal(err)
				}
				if len(routes) != 1 || routes[0].Slug != visible.Slug {
					t.Fatalf("list = %+v, want only the enabled route", routes)
				}
			})

			t.Run("rename changes the hash", func(t *testing.T) {
				db := open(t)

				route, err := db.Create(t.Context(), CreateRequest{Name: "Before", GPX: exampleGPX(t)})
				if err != nil {
					t.Fatal(err)
				}
				after := "After"
				updated, err := db.Update(t.Context(), route.Slug, UpdateRequest{Name: &after})
				if err != nil {
					t.Fatal(err)
				}
				if updated.ContentHash == route.ContentHash {
					t.Error("hash unchanged after a rename; it would never sync")
				}
			})

			t.Run("targets round trip", func(t *testing.T) {
				db := open(t)

				only := []string{"garmin:wilant"}
				if _, err := db.Create(t.Context(), CreateRequest{
					Name: "Private", GPX: exampleGPX(t), Targets: &only,
				}); err != nil {
					t.Fatal(err)
				}

				routes, _, err := db.List(t.Context())
				if err != nil {
					t.Fatal(err)
				}
				if len(routes) != 1 || routes[0].Targets == nil {
					t.Fatalf("targets lost: %+v", routes)
				}
				if got := *routes[0].Targets; len(got) != 1 || got[0] != "garmin:wilant" {
					t.Errorf("targets = %v", got)
				}
			})

			t.Run("slug disambiguation", func(t *testing.T) {
				db := open(t)

				first, err := db.Create(t.Context(), CreateRequest{Name: "Same Name", GPX: exampleGPX(t)})
				if err != nil {
					t.Fatal(err)
				}
				second, err := db.Create(t.Context(), CreateRequest{Name: "Same Name", GPX: exampleGPX(t)})
				if err != nil {
					t.Fatal(err)
				}
				if first.Slug == second.Slug {
					t.Fatalf("both got %q", first.Slug)
				}
			})

			t.Run("delete", func(t *testing.T) {
				db := open(t)

				route, err := db.Create(t.Context(), CreateRequest{Name: "Doomed", GPX: exampleGPX(t)})
				if err != nil {
					t.Fatal(err)
				}
				if err := db.Delete(t.Context(), route.Slug); err != nil {
					t.Fatalf("delete: %v", err)
				}
				if err := db.Delete(t.Context(), route.Slug); !errors.Is(err, ErrNotFound) {
					t.Errorf("second delete: %v, want ErrNotFound", err)
				}
				if _, err := db.GPX(t.Context(), route.Slug); !errors.Is(err, ErrNotFound) {
					t.Errorf("GPX after delete: %v, want ErrNotFound", err)
				}
			})

			t.Run("rejects bad gpx", func(t *testing.T) {
				db := open(t)
				if _, err := db.Create(t.Context(), CreateRequest{Name: "Bad", GPX: []byte("nope")}); err == nil {
					t.Error("bad GPX accepted")
				}
			})
		})
	}
}
